---
title: "Untitled"
author: "Chi Lam"
date: "September 23, 2015"
output: pdf_document
---
## Synopsis 

## Libraries needed
```{r libs, message = FALSE, results=FALSE}
library(dplyr)
library(ggplot2)
```

## Data Processing
### Loading data
```{r loadNOrg, cache=TRUE, message = FALSE}

#loading data
stormStat <- read.csv("repdata-data-StormData.csv.bz2")
```

### Statistics Generation
```{r dataProc}
#interpret the prop and crop damage exponents
ltrexp <- c("", " ", "-", "?", "+", "0", "1", "2", "3", "4", 
	"5", "6", "7", "8", "B", "h", "H", "k", "K", "m", "M")
num10pwr <- c(0, 0, 0, 0, 0, 0, 1, 2, 3, 4,
	5, 6, 7, 8, 9, 2, 2, 3, 3, 6, 6)
stormStat$PROPDMGTTL <- stormStat$PROPDMG * 10^( num10pwr[match(stormStat$PROPDMGEXP, ltrexp)] )
stormStat$CROPDMGTTL <- stormStat$CROPDMG * 10^( num10pwr[match(stormStat$CROPDMGEXP, ltrexp)] )

#combining deaths with injuries, and property with crop damages
stormStat$humanHarm <- stormStat$FATALITIES * 50 + stormStat$INJURIES
stormStat$econDmg <- stormStat$PROPDMGTTL + stormStat$CROPDMGTTL

#generate the stats
stormStatSum <- stormStat %>% group_by(EVTYPE) %>% 
    summarize(frequency=n(), fatalities=sum(FATALITIES), injuries=sum(INJURIES), 
              humanHarm=sum(humanHarm), propDmg=sum(PROPDMGTTL), cropDmg=sum(CROPDMGTTL),
              econDmg=sum(econDmg));
stormStatSumByFatal <- stormStatSum[order(-stormStatSum$fatalities), ]
```

## Results
### Fatalities
```{r fatalStats}
stormStatSumByFatalIdx <- order(-stormStatSum$fatalities)
top10fatal <- head(stormStatSum[stormStatSumByFatalIdx, c("EVTYPE", "frequency", "fatalities")], n=10)
top10fatal$EVTYPE <- factor(top10fatal$EVTYPE, levels = top10fatal$EVTYPE)
qplot(y=fatalities,x=EVTYPE, fill=frequency, data=top10fatal, geom="bar", stat="identity") + coord_flip() + 
    labs(title = "Top 10 Events by Fatalities", y="Fatalities", x="Event Type")
```

### Injuries
```{r injuryStats}
stormStatSumByInjurIdx <- order(-stormStatSum$injuries)
top10injur <- head(stormStatSum[stormStatSumByInjurIdx, c("EVTYPE", "frequency", "injuries")], n=10)
top10injur$EVTYPE <- factor(top10injur$EVTYPE, levels = top10injur$EVTYPE)
qplot(y=injuries, x=EVTYPE, fill=frequency, data=top10injur, geom="bar", stat="identity") +     coord_flip() + 
    labs(title = "Top 10 Events by Injuries", y="Injuries", x="Event Type")
```

### Economic Losses
```{r econStats}
stormStatSumByEconIdx <- order(-stormStatSum$econDmg)
top10loss <- head(stormStatSum[stormStatSumByEconIdx, c("EVTYPE", "frequency", "econDmg" )], n=10)
top10loss$EVTYPE <- factor(top10loss$EVTYPE, levels = top10loss$EVTYPE)
qplot(y=econDmg, x=EVTYPE, fill=frequency, data=top10loss, geom="bar", stat="identity") +     coord_flip() + 
    labs(title = "Top 10 Events by Economic Loss", y="Economic Loss(USD)", x="Event Type")
```

##Conclusion